"""End-to-End Live Integration Test for Linux Substitution Client and Go Backend."""

from datetime import datetime
import hashlib
import json
import os
from pathlib import Path
import signal
import subprocess
import sys
import time
import urllib.request
import urllib.error


def run_e2e_live_test():
    print("==================================================")
    print("      LIVE E2E PIPELINE TEST (LINUX / WAYLAND)    ")
    print("==================================================")

    repo_root = Path(__file__).resolve().parent.parent
    client_dir = repo_root / "client_linux"
    bin_server = repo_root / "bin" / "isbn-bridge-server"

    # Ensure Go server is built
    if not bin_server.is_file():
        print("Building Go server binary...")
        subprocess.run(["go", "build", "-o", str(bin_server), "./cmd/server"], cwd=str(repo_root), check=True)

    # Clean any leftover secrets
    secret_file = repo_root / "local_secret.txt"

    print("\n1. Starting Linux client via uv...")
    test_env = os.environ.copy()
    test_env["ISBN_BRIDGE_NO_NOTIFY"] = "1"
    test_env["ISBN_BRIDGE_NO_SOUND"] = "1"
    test_env["ISBN_BRIDGE_NO_TYPING"] = "1"

    client_proc = subprocess.Popen(
        ["uv", "run", "client-linux"],
        cwd=str(client_dir),
        env=test_env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    try:
        # 2. Wait for client and server to start up (up to 6s)
        client_ready = False
        server_ready = False
        secret = ""

        print("2. Waiting for services to initialize...")
        for _ in range(30):
            time.sleep(0.2)
            if not client_ready:
                try:
                    with urllib.request.urlopen("http://127.0.0.1:8766/status", timeout=0.5) as resp:
                        if resp.status == 200:
                            client_ready = True
                            print("   -> Linux client HTTP listener active on :8766")
                except Exception:
                    pass

            if not server_ready:
                try:
                    with urllib.request.urlopen("http://127.0.0.1:8765/health", timeout=0.5) as resp:
                        if resp.status == 200:
                            server_ready = True
                            print("   -> Go server active on :8765")
                except Exception:
                    pass

            if client_ready and server_ready:
                break

        assert client_ready, "Linux client failed to start within timeout"
        assert server_ready, "Go server failed to start within timeout"

        # Read generated local secret
        assert secret_file.is_file(), "local_secret.txt was not generated by server"
        secret = secret_file.read_text(encoding="utf-8").strip()
        print(f"   -> Forwarder secret loaded ({len(secret)} chars)")

        # 3. Test QR Show & Hide on Linux client
        print("\n3. Testing POST /qr/show and /qr/hide on Linux client...")
        req_show = urllib.request.Request(
            "http://127.0.0.1:8766/qr/show",
            data=b"",
            headers={"X-ISBN-Bridge-Local": secret},
            method="POST",
        )
        with urllib.request.urlopen(req_show, timeout=2.0) as resp:
            assert resp.status == 200
            print("   -> POST /qr/show: SUCCESS (200 OK)")

        time.sleep(0.3)

        req_hide = urllib.request.Request(
            "http://127.0.0.1:8766/qr/hide",
            data=b"",
            headers={"X-ISBN-Bridge-Local": secret},
            method="POST",
        )
        with urllib.request.urlopen(req_hide, timeout=2.0) as resp:
            assert resp.status == 200
            print("   -> POST /qr/hide: SUCCESS (200 OK)")

        # 4. Fetch live token and QR from Go server
        print("\n4. Testing Go server pairing endpoints...")
        with urllib.request.urlopen("http://127.0.0.1:8765/pair?format=json", timeout=2.0) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            token = data["token"]
            print(f"   -> Active secret token: {token[:8]}... (length: {len(token)})")

        with urllib.request.urlopen("http://127.0.0.1:8765/qr.png", timeout=2.0) as resp:
            qr_bytes = resp.read()
            assert len(qr_bytes) > 100
            assert resp.headers.get("Content-Type") == "image/png"
            print(f"   -> Go server generated valid in-memory QR PNG ({len(qr_bytes)} bytes)")

        # 5. Full round-trip: Mobile Scan -> Go Server -> Linux Client
        print("\n5. Testing Mobile Scan -> Go Server -> Linux Client...")
        isbn = "9780306406157"
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        auth_raw = f"{isbn}|{ts}|{token}".encode("utf-8")
        sig = hashlib.sha256(auth_raw).hexdigest()

        scan_req = urllib.request.Request(
            "http://127.0.0.1:8765/isbn",
            data=isbn.encode("utf-8"),
            headers={
                "Authorization": f"Bearer {sig}",
                "Timestamp": ts,
                "Content-Type": "text/plain; charset=utf-8",
            },
            method="POST",
        )
        with urllib.request.urlopen(scan_req, timeout=3.0) as resp:
            body = resp.read().decode("utf-8")
            assert resp.status == 200
            assert body == "OK"
            print(f"   -> Mobile scan accepted by Go server (200 OK)")

        # Check client armed state
        time.sleep(0.3)
        with urllib.request.urlopen("http://127.0.0.1:8766/status", timeout=2.0) as resp:
            client_status = json.loads(resp.read().decode("utf-8"))
            print(f"   -> Linux client state: {client_status}")
            # Note: depending on whether the active window matches target,
            # either it pasted immediately or it's armed. Both are valid!

        # 6. Test Trigger Endpoint
        print("\n6. Testing Trigger Endpoint (/trigger)...")
        trigger_req = urllib.request.Request(
            "http://127.0.0.1:8766/trigger",
            headers={"X-ISBN-Bridge-Local": secret},
            method="POST",
        )
        with urllib.request.urlopen(trigger_req, timeout=2.0) as resp:
            assert resp.status == 200
            print("   -> POST /trigger: SUCCESS (200 OK)")

        # 7. Test Replay Attack Prevention
        print("\n7. Testing Security: Replay Attack...")
        replay_req = urllib.request.Request(
            "http://127.0.0.1:8765/isbn",
            data=isbn.encode("utf-8"),
            headers={
                "Authorization": f"Bearer {sig}",
                "Timestamp": ts,
                "Content-Type": "text/plain; charset=utf-8",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(replay_req, timeout=3.0) as resp:
                raise AssertionError("Replay attack was unexpectedly accepted!")
        except urllib.error.HTTPError as e:
            assert e.code == 409, f"Expected 409 Conflict for replay rejection, got {e.code}"
            print(f"   -> Replay attack correctly rejected with HTTP {e.code} Conflict")

        # 8. Test Rate Limiting
        print("\n8. Testing Security: LAN Rate Limiting (429 Too Many Requests)...")
        rate_limit_req = urllib.request.Request(
            "http://127.0.0.1:8765/isbn",
            data=b"9780306406157",
            headers={
                "Authorization": "Bearer badbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadb",
                "Timestamp": ts,
                "Content-Type": "text/plain; charset=utf-8",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(rate_limit_req, timeout=3.0) as resp:
                raise AssertionError("Rate limit was unexpectedly not enforced!")
        except urllib.error.HTTPError as e:
            assert e.code == 429, f"Expected 429 Too Many Requests, got {e.code}"
            print(f"   -> Rate limit correctly enforced: HTTP {e.code} Too Many Requests")

        # 9. Test Invalid ISBN Checksum
        print("\n9. Testing Security: Invalid ISBN Checksum (waiting 10s for rate limit window)...")
        time.sleep(10.5)
        invalid_isbn = "9780306406158"  # Wrong check digit
        ts2 = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        auth_raw_inv = f"{invalid_isbn}|{ts2}|{token}".encode("utf-8")
        sig_inv = hashlib.sha256(auth_raw_inv).hexdigest()
        inv_req = urllib.request.Request(
            "http://127.0.0.1:8765/isbn",
            data=invalid_isbn.encode("utf-8"),
            headers={
                "Authorization": f"Bearer {sig_inv}",
                "Timestamp": ts2,
                "Content-Type": "text/plain; charset=utf-8",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(inv_req, timeout=3.0) as resp:
                raise AssertionError("Invalid ISBN was unexpectedly accepted!")
        except urllib.error.HTTPError as e:
            assert e.code == 400
            print(f"   -> Invalid checksum correctly rejected with HTTP {e.code}")

        print("\n==================================================")
        print("  ALL LIVE INTEGRATION TESTS PASSED SUCCESSFULLY! ")
        print("==================================================")

    finally:
        print("\nShutting down client and managed Go server...")
        client_proc.send_signal(signal.SIGINT)
        try:
            client_proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            client_proc.kill()
        print("Cleaned up processes.")


if __name__ == "__main__":
    run_e2e_live_test()
