[project]
name = "client-linux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel Biasiotto", email = "mail@denial.in.net" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
client-linux = "client_linux:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
